---
title: "Fiddler Crabs"
author: "Leilanie Rubinstein & Kaiju Morquecho"
format: html
execute: 
  warning: false
  echo: false
editor_options: 
  chunk_output_type: console
---

```{r}
library(lterdatasampler)
library(kableExtra)
library(tidyverse)
```

## This is a plot of crab carapace sizes by latitude.

```{r}
library(tidyverse)

ggplot(data = pie_crab, aes(x = latitude, y = size)) +
  geom_point() +
  labs(caption = "this is my caption")
```

## This is a summary table of containing the mean and standard deviation of crab carapace sizes in mm, and the number of crabs per site.

```{r}
pie_crab_summary <- pie_crab %>%
  dplyr::group_by(site) %>%
  dplyr::summarise(mean = round(mean(size), 2),
                   sd = round(sd(size), 2),
                   count = n()) %>%
  kable(col.names = c("site", "mean size (mm)", "standard deviation (mm)", "count"))
pie_crab_summary

```

#### This data was obtained from the package {lterdatasampler}: Educational Dataset Examples from the Long Term Ecological Research Program.